
# language: node_js
# node_js:
#   - '8'
# deploy:
#   provider: heroku
#   api_key:
#     secure: $HEROKU_KEY
#   app:
#     develop: is2-authentication-develop
# before_script:
#   - "npm info dredd version"
#   - "cd TEST"
# script:
#   - make test
language: node_js
node_js:
  - '8'
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app:
    develop: is2-authentication-develop
install:
  - "npm install"
before_script:
  - "npm info dredd version"
after_script:
  - "mocha --exit"
