language: node_js
node_js:
  - '8'
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app:
    develop: is2-authentication-develop
install:
  - "npm install --no-optional"
before_script:
  - "npm info dredd version"
